// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
)

type Episode struct {
	ID               []byte
	AudioUrl         string
	AudioLengthBytes int64
	Description      sql.NullString
	Duration         sql.NullInt64
	FeedID           string
	ReleasedAt       sql.NullTime
	Thumbnail        sql.NullString
	Title            string
	VideoUrl         sql.NullString
}

type Feed struct {
	ID          []byte
	CreatedAt   sql.NullTime
	Description sql.NullString
	Title       string
	UpdatedAt   sql.NullTime
	Link        string
	Xml         string
}
